### PR TITLE
Fix assertion

### PR DESCRIPTION
**Pull request by nkakouros**

### CODE REVIEW

**Comment by trombik** [comment]
@nkakouros does this work for you? version 2.2.2 includes your fix. https://github.com/trombik/ansible-role-apt_repo

**Comment by nkakouros** [comment]
Yes, it seems to work ok.

**Comment by nkakouros** [comment]
@trombik Is the repo you pointed at the one we should be using now? Is this one here deprecated?

**Comment by trombik** [comment]
@nkakouros I used to maintain these repos (reallyenglish), but does not have access to them anymore. you should be able to find corresponding roles under [my own account (trombik)](https://galaxy.ansible.com/trombik). if not, it's a bug.

**Comment by nkakouros** [comment]
OK, thanks.

**Pull request closed without merging**
